' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

hide footbox

autonumber "<font color=red><b>[00]"

title Clock mocking support (feature view)

legend top left
| <#LightGreen>  | score::time feature |
| <#LightSalmon> | application         |
endlegend

!pragma teoz true
box "ECU" #f0f5f5
  box "Application process" #e6ffe6
    participant "Application"              as app   #LightSalmon
    participant "Clock<Tag>\n(mock)"  as clock #LightGreen
  end box
end box

note over app, clock
  Applies to Vehicle Clock, Local Clock
  and Absolute Clock
end note

== Test setup ==
app -> clock : inject mock

== Application reads time ==
app -> clock : now()
clock --> app : controlled Snapshot\n(predetermined TimePoint + status)

@enduml
