' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

hide footbox

autonumber "<font color=red><b>[00]"

title Local Time read (feature view)

legend top left
| <#LightGreen>  | score::time feature  |
| <#LightSalmon> | application          |
| <#LightGrey>   | OS / local time base |
endlegend

!pragma teoz true
box "ECU" #f0f5f5
  box "Application process" #e6ffe6
    participant "Application"                as app #LightSalmon
    participant "score::time::SteadyClock\n/ HighResSteadyClock\n/ SystemClock" as lc  #LightGreen
  end box
  participant "OS" as os #LightGrey
end box

== Steady Clock ==
app -> lc : now()
lc -> os : CLOCK_MONOTONIC\n(std::chrono::steady_clock)
os --> lc : TimePoint
lc --> app : Snapshot (TimePoint)

== System Clock ==
app -> lc : now()
lc -> os : CLOCK_REALTIME\n(std::chrono::system_clock)
os --> lc : TimePoint
note left
  Kept aligned to Absolute Time
  by score::time
end note
lc --> app : Snapshot (TimePoint)

== High-Resolution Steady Clock ==
app -> lc : now()
lc -> os : ClockCycles
os --> lc : TimePoint
lc --> app : Snapshot (TimePoint)

@enduml
