@startuml dd_deployment_diagram

title Deployment view

node "Application Layer" {
    [Business logic] as app_bl
    [mw::time::svt] <<library>> as mw
}
node "time_slave" <<daemon>> {
    [gptp_engine] as gptp_engine
}
node "time_daemon" <<daemon>> {
    [MessageBroker]  as msg_broker
    [VerificationMachine]  as verification_machine
    [PTP machine] as ptp_machine
    [IPC] <<score::communication>> as ipc
}

gptp_engine -[#blue]-> ptp_machine : gPTP time updates\n(via score::memory::shared)
ptp_machine -[#green]-> verification_machine: Time information
verification_machine -[#green]-> ipc: Time information
ipc -[#green]-> mw: Time information\n(via score::memory::shared)
mw-[#orange]-> app_bl : Now()

@enduml
