/********************************************************************************
 * (c) 2025 ETAS GmbH. All rights reserved.
 ********************************************************************************/

#ifndef FLATCFG_FLATCFG_H
#define FLATCFG_FLATCFG_H

#include "config/daemon_iterator.h"
#include "config/identifier.h"
#include "config/process_iterator.h"
#include "config/version.h"
#include "flatcfg_error.h"
#include "_export.h"

#include "flatbuffers/score.h"

#include "score/result/result.h"

#include <algorithm>
#include <cctype>
#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <memory_resource>
#include <string>
#include <string_view>
#include <vector>

namespace flatcfg
{

/// @brief Class providing access to the configuration data of an application or
///        of a daemon.
/// @details FlatCfg provides access to the raw data in configurations relevant
///          to the application or daemon. Parsing this data is up to the user.
class FlatCfg
{
public:
    /// @brief Deleter used to destroy memory allocated by load.
    struct Deleter
    {
    public:
        /// @brief Construct deleter from any pmr allocator.
        Deleter(std::pmr::polymorphic_allocator<void> alloc,
                std::size_t size) noexcept;

        /// @brief Destroy object and deallocate memory using stored allocator.
        void
        operator()(unsigned char *ptr) noexcept;

    private:
        /// @brief Store allocator with which to deallocate.
        std::pmr::polymorphic_allocator<void> m_alloc;

        /// @brief Size to pass to deallocate.
        std::size_t m_size;
    };

    /// @brief Create a FlatCfg instance from function cluster information
    ///        generated by the flatbuffers compiler.
    template <class T>
    static score::Result<FlatCfg>
    FromFcInfo(const flatbuffers::score::FcBase<T>& fcInfo) noexcept;

    /// @brief Copy (and move) constructible.
    /// @note  No dedicated move constructor because we don't want to invalidate
    ///        the existing instance.
    // RULECHECKER_comment(1, 1, check_incomplete_data_member_construction, "All data members are constructed.", false)
    FlatCfg(const FlatCfg&) = default;

    /// @brief Copy (and move) assignable.
    /// @note  No dedicated move assignment operator because we don't want to
    ///        invalidate the existing instance.
    FlatCfg&
    operator=(const FlatCfg&) = default;

    /// @brief Obtain an iterator which will yield identifiers to all
    ///        configurations relevant for a daemon.
    score::Result<config::DaemonIterator>
    daemonConfig() const noexcept;

    /// @brief Obtain an iterator which will yield identifiers to all
    ///        configurations relevant for a process of the application.
    score::Result<config::ProcessIterator>
    processConfig() const noexcept;

    /// @brief Get the number of bytes that would be requested from the
    ///        allocator if the same identifier were passed to load(...).
    static score::Result<std::size_t>
    size(const config::Identifier& id) noexcept;

    /// @brief Load the raw data from the configuration referenced by the given
    ////       identifier into memory, using the user-provided allocator for any
    ///        dynamic memory allocations.
    static score::Result<std::unique_ptr<unsigned char[], Deleter>>
    load(const config::Identifier& id,
         std::pmr::polymorphic_allocator<void> alloc) noexcept;

private:
    /// @brief Create a FlatCfg instance from function cluster name and version
    ///        information.
    /// @note  If an error occurs, it is written to resOut and the instance is considered invalid.
    /// @pre   Name is not empty, it must match "[a-zA-Z]+", and it must not
    ///        exceed 16 characters.
    FlatCfg(std::string_view name, config::Version version,
            score::ResultBlank *resOut) noexcept;

public:
    /// @brief     Constructor
    /// @details   Constructor for the FlatCfg class
    /// @param[in] fcInfo FC Information from FlatBuffers generated header
    template <typename T>
    // RULECHECKER_comment(1, 1, check_incomplete_data_member_construction, "All data members are constructed.", false)
    FlatCfg(const flatbuffers::score::FcBase<T>& fcInfo) noexcept
        : m_functionClusterName(fcInfo.name()),
          m_functionClusterNameLowerCase(fcInfo.name()),
          m_functionClusterMajorVersion(fcInfo.versionMajor()),
          m_functionClusterMinorVersion(fcInfo.versionMinor())
    {
        // fcName in the file path is expected to be lower-case
        // currently flatbuffers requires (and provides) upper-case fcName
        // we need both
        using std::begin;
        using std::end;
        std::transform(begin(m_functionClusterName), end(m_functionClusterName),
                       begin(m_functionClusterNameLowerCase), [](unsigned char c) {
            return std::tolower(static_cast<int>(c)); });
    }

    /// @brief     Returns the available SWClusters for the requested FC
    /// @details   getSwClusterList searches the configuration path for the application
    ///            and returns all SWClusters for the requested fc.
    /// @return    Names of the SWClusters that are available for the fc,
    ///            error if more than one process is configured in the configuration path.
    /// @error FlatCfgErrorCode::kConfigFiles Returned if globbing for the config file in the given path fails.
    /// @error FlatCfgErrorCode::kInvalidConfigPath Returned if the ENV-variable that points to the path is not defined or the given path does not exist.
    virtual score::Result<std::vector<std::string>>
    getSwClusterList() noexcept;

    /// @brief     Load
    /// @param[in] SwClusterName to load
    /// @details   Allocate memory and load the config file for the requested SWCluster
    ///            Memory is allocated and client have to take care about releasing when not needed
    /// @return    Shared pointer to FlatBuffer, error when file can't be loaded
    /// @error FlatCfgErrorCode::kFileAccessError Returned if the file cannot be accessed.
    /// @error FlatCfgErrorCode::kFileEmpty Returned if the file is empty.
    /// @error FlatCfgErrorCode::kFileNotFound Returned if the file cannot be found.
    /// @error FlatCfgErrorCode::kInvalidSWCLName Returned if the given SwClusterName cannot be found.
    /// @error FlatCfgErrorCode::kMemoryAllocationFailed Returned if there is not enough memory to load the configurations.
    virtual score::Result<std::shared_ptr<void>>
    load(const std::string& SwClusterName) noexcept;

    /// @brief Virtual destructor.
    virtual ~FlatCfg() noexcept = default;

private:
    /// Function cluster information
    std::string m_functionClusterName;
    std::string m_functionClusterNameLowerCase;
    std::int32_t m_functionClusterMajorVersion {};
    std::int32_t m_functionClusterMinorVersion {};

    /// Shared map which holds metadata for all SW Clusters
    std::map<std::string, std::string> m_SwClusterPathMap;

    /// Name of the environment variable that holds the path to the configuration files
    // Type is a char* as it is only used with getenv which expects char*
    static const std::string_view envVar_configPath;

    /// Wildcard pattern to match the configuration filenames (FC will be preponed later)
    static const std::string_view configFileGlobPattern;

    /// @brief     Get the path to the configuration files
    /// @details   This function determines the path to the configuration files and checks if it exists.
    ///            The path is read from the ENV-variable defined in FlatCfg::envVar_configPath.
    /// @return    Path to the configuration files,
    ///            error if it cannot be determined or does not exist.
    /// @error FlatCfgErrorCode::kInvalidConfigPath Returned if the ENV-variable that points to the path is not defined or the given path does not exist.
    score::Result<std::string> getConfigPath() const noexcept;

    /// @brief     Get a list of all config filenames for the requested fc that are stored in the configPath
    /// @details   This functions reads all config filenames for the requested fc that are stored in the given path.
    /// @note      As the used glob only has limited filtering power, there still may be false positives which have
    ///            to be filtered out (files with incorrect names that are nonetheless matched by the wildcard pattern)
    /// @param[in] configPath Path in which the config files are searched.
    /// @return    Names of the configuration files that are available for the fc,
    ///            error if searching fails.
    /// @error FlatCfgErrorCode::kConfigFiles Returned if globbing for the config file in the given path fails.
    score::Result<std::vector<std::string>>
    getConfigFiles(const std::string& configPath) const noexcept;

    /// @brief     Checks if all configurations in the list belong to one process and returns the SWCluster names
    /// @details   This function checks the given list of filenames as follows:
    ///            - Filenames are conform to the rules
    ///            - Only one process is configured with the given files
    ///            - SWCluster is not empty
    ///            If the checks are successful a list of all SWClusters that are configured in the list is returned.
    /// @param[in] fileList List of files to be checked.
    /// @return    List of SWClusters for which a configuration was found,
    ///            error if a check failed
    /// @error FlatCfgErrorCode::kInvalidFileName Returned if the config files name is invalid.
    /// @error FlatCfgErrorCode::kMultipleProcessesInPath Returned If the configuration folder contains configurations for more than one process.
    score::Result<std::vector<std::string>>
    checkFilesAndGetSwClusterList(const std::vector<std::string>& fileList) noexcept;
};

template <class T>
score::Result<FlatCfg>
FlatCfg::FromFcInfo(const flatbuffers::score::FcBase<T>& fcInfo) noexcept
{
    score::ResultBlank res;
    config::Version version { fcInfo.versionMajor(), fcInfo.versionMinor() };
    FlatCfg cfg { fcInfo.name(), version, &res };
    if (res)
    {
        return cfg;
    }
    else
    {
        return score::MakeUnexpected<FlatCfg>(res.error());
    }
}

} // namespace flatcfg

#endif  // FLATCFG_FLATCFG_H
