load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "Timestamp_UT",
    srcs = [
        "Timestamp_UT.cpp",
    ],
    deps = [
        "//src/tsync-lib:tsync_if",
        "@googletest//:gtest_main",
    ]
)
