# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
# Based on the conf.py generated by the docs() macro; extends it with
# required_in_id so that feat_arc_sta__time__* / feat_arc_dyn__time__* IDs
# are accepted under docs/features/architecture/ (feature part "time" is
# declared as valid here rather than enforced via the folder path).

project = "S-CORE Time"
project_url = "https://eclipse-score.github.io/time"
version = "0.0.0"

extensions = ["score_sphinx_bundle"]

# Allow IDs containing "time" to live outside a "time/" subdirectory.
required_in_id = ["time"]
